version: '3.8'

services:
  f1_sponsorship_db:
    image: mysql:8.0
    container_name: mysql-sponsorship
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sponsorship123
      MYSQL_DATABASE: f1_sponsorship
    ports:
      - "3307:3306"
    volumes:
      - sponsorship-data:/var/lib/mysql
      - ./data/f1_sponsorship.sql:/docker-entrypoint-initdb.d/f1_sponsorship.sql
    networks:
      - f1-network

  f1_teams_drivers_db:
    image: mysql:8.0
    container_name: mysql-teams-drivers
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teamsdrivers123
      MYSQL_DATABASE: f1_teams_drivers
    ports:
      - "3308:3306"
    volumes:
      - teams-drivers-data:/var/lib/mysql
      - ./data/f1_teams_drivers.sql:/docker-entrypoint-initdb.d/f1_teams_drivers.sql
    networks:
      - f1-network

  # Service Discovery
  eureka-server:
    build:
      context: ./EurekaServer
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-server
    networks:
      - f1-network

  # API Gateway
  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - f1-network

  # Microservices
  team_drivers_service:
    build:
      context: ./TeamDrivers
      dockerfile: Dockerfile
    container_name: team_drivers_service
    ports:
      - "8082:8082"
    depends_on:
      - f1_teams_drivers_db
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=team-drivers-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-teams-drivers:3306/f1_teams_drivers
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=teamsdrivers123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - f1-network
    restart: on-failure

  sponsorship_service:
    build:
      context: ./Sponsorship
      dockerfile: Dockerfile
    container_name: sponsorship_service
    ports:
      - "8083:8083"
    depends_on:
      - f1_sponsorship_db
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=sponsorship-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-sponsorship:3306/f1_sponsorship
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=sponsorship123
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - f1-network
    restart: on-failure

networks:
  f1-network:
    driver: bridge

volumes:
  sponsorship-data:
  teams-drivers-data: